version: 2

updates:
  - package-ecosystem: bundler
    directory: "/"
    schedule:
      interval: weekly
    open-pull-requests-limit: 100
    groups:
      minor_versions:
        update-types:
          - 'minor'
          - 'patch'  
  - package-ecosystem: github-actions
    directory: '/'
    schedule:
      interval: weekly