# This file is for shopify internal development, feel free to ignore.
name: recordstore

up:
  - ruby
  - bundler

commands:
  test:
    syntax:
      argument: file
      optional: args...
    desc:   'run tests'
    run: |
      if [[ $# -eq 0 ]]; then
        bundle exec rake test
      else
        bundle exec ruby -W0 -Itest "$@"
      fi
  style:
    syntax: ""
    desc:   'Run rubocop'
    run:    'bin/rubocop'
