name: CI

on: [push, pull_request]

env:
  SRB_SKIP_GEM_RBIS: true

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby: [ 3.0, 3.1, 3.2 ]
    name: Test Ruby ${{ matrix.ruby }}
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          sudo apt-get update && sudo apt-get install build-essential libcurl4-openssl-dev
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: rubocop
        run: bin/rubocop --version && bin/rubocop
      - name: setup
        run: bin/setup
      - name: test
        run: bundle exec rake test
